### PR TITLE
CORS added in attacks

### PR DESCRIPTION
**Pull request by yaman-694**
hacktober fest

### CODE REVIEW

**Comment by Prashant-Bhapkar** [comment]
Hi @yaman-694 
1. Please add your contribution according to alphabetical order
2. Reflect those changes on the first page (README.md) of the repository

**Comment by yaman-694** [comment]
hi @Prashant-Bhapkar 
I didn't get you can please me explain about alphabetical order?

**Comment by yaman-694** [comment]
Updated

**Comment by Prashant-Bhapkar** [comment]
Hi @yaman-694 
Thank you for your contribution.

Looking forward add many more...

**Comment by yaman-694** [comment]
thanks!!
but this is not reflecting on my hacktober dashboard

**Comment by Prashant-Bhapkar** [comment]
It may take time to reflect.

**Pull request merged**
