### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by abhisek2-eng**

### CODE REVIEW

**Comment by Prashant-Bhapkar** [comment]
Update the changes in a specific folder and then update it with the README.md path.

**Comment by abhisek2-eng** [comment]
accept it please

**Comment by Prashant-Bhapkar** [comment]
Hi Abhisek,
1) Add your tools to specified folders like masscan in the network security folder and shodan in the search engine folder.
2) Update both README.md files (first main page and second in the respective folder)

**Comment by abhisek2-eng** [comment]
Done.

**Comment by abhisek2-eng** [comment]
Thank you!

**Pull request closed without merging**
